//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TipoParkinson
    {
        public tbl_TipoParkinson()
        {
            this.tbl_Pacientes = new HashSet<tbl_Pacientes>();
        }
    
        public int idTipoParkinson { get; set; }
        public string Tipo_Parkinson { get; set; }
    
        public virtual ICollection<tbl_Pacientes> tbl_Pacientes { get; set; }
    }
}
