//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImagenesPacientes
    {
        public int idImagenPaciente { get; set; }
        public string fileName { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<System.DateTime> fechaCargada { get; set; }
    
        public virtual tbl_Pacientes tbl_Pacientes { get; set; }
    }
}
